### ISSUE TITLE
Provide restricted Github auth route

### ISSUE THREAD

**Issue by aubergene** [editdata/app.editdata.org#78]
When I sign in with Github it asks for read and write access to public and private repositories. This is too permissive in my opinion. I would like to be able to only grant read access to public repos.

**Comment by sethvincent** [comment]
We could certainly make it so that we're only requesting read/write access to public repos.

The primary use case for this project is to allow users to edit csv/json files in their repos and commit those changes back.

What would be the use case for having only read access to repos?

**Comment by aubergene** [comment]
Sorry, I was probably being overly concerned about the security impact, as my employer is very strict. However we would probably run our own instance internally anyhow. 

I guess having a 'no scope' login would mean it would be easy to try it out the interface without any risk or requirement for a repo.

**Comment by sethvincent** [comment]
That makes sense 😄 . A no scope login is a good idea. 

I'll keep this open and will either implement a no scope option in this project, or may alternately create something like demo.editdata.org where people can upload/download files, work with public files, etc., without requiring github auth.
