### ISSUE TITLE
Commit to branch

### ISSUE THREAD

**Issue by olafveerman** [editdata/app.editdata.org#79]
Great project @sethvincent ! I encountered an issue when saving a change on app.editdata.org. Is this a known issue, anything I am doing wrong?

### Expected behavior
When I open a file on a branch (eg `data`), I expect edits to be saved to a commit on that same branch.

### Actual behavior
The commit is pushed to the `master` branch of the project.

**Comment by sethvincent** [comment]
@olafveerman Thanks for reporting this!

My guess right now is that the `updatedGitHubFile` action (https://github.com/editdata/app.editdata.org/blob/master/actions/save.js#L89) isn't being passed a branch.

I'll try and get that fixed soon!

**Comment by sethvincent** [comment]
This should now be fixed!

There may be some other branch-related bugs I'll need to check out, but it'll now read and update files from a branch as expected.
